module.exports = {
  // isArray: assert.isArray,
  // isJSUrl: assert.isJSUrl,
  // isEmpty: assert.isEmpty,
  // isObject: assert.isObject,
  // isString: assert.isString,
  // isImgUrl: assert.isImgUrl,
  // isCSSUrl: assert.isCSSUrl,
  // isHTMLUrl: assert.isHTMLUrl,
  // rangeEqual: assert.rangeEqual,
  // isEmptyArray: assert.isEmptyArray,
  // isEmptyObject: assert.isEmptyObject,
  ...require('./assert'),
  Link: require('./link'),
  sleep: require('./sleep'),
  quest: require('./quest'), // superagent的封装
  unique: require('./unique'), // 去重,
  initPage: require('./init-page'),
  buildPath: require('./build-path'),
  removeDir: require('./remove-dir'),
  hasUnlinks: require('./has-unlinks'),
  dateFormat: require('./date-format'),
  BunchThread: require('./bunch-thread'),
  moneyFormat: require('./money-format'),
  readDirSync: require('./read-dir-sync'),
  BunchLinking: require('./bunch-linking'),
  readFileSync: require('./read-file-sync'),
  writeFileSync: require('./write-file-sync'),
  recordUsedApi: require('./record-used-api'),
  hasRefreshLinks: require('./has-refresh-links'),
  removeSiblingDir: require('./remove-sibling-dir'),
  getPathSeparator: require('./get-path-separator'), // 获取路径分隔符
  requestApiInBunch: require('./request-api-in-bunch'),
}
